# NUMPY

## I. Numerical Computing with Numpy

The "*data*" in *Data Analytics* is usually numerical data (i.e. stock prices, sales figures, sensor measurements, sports scores, database tables, etc). The [Numpy](https://numpy.org/) library proides data structures, functions, and other tools for numerical computing in Python. 

### i. Working with Numberical Data

Let's see an example...
> Suppose we want to use climate data like the temperature, rainfall, and humidity to determine if a region is well suited for growing apples. A simple approach for doing this would be to formulate the relationship between the annual yield of apples (tons per hectare) and the climatic conditions like the average temperature (in degrees Fahrenheit), rainfall (in millimeters) & average relative humidity (in percentage) as a linear equation.
>
> `yield_of_apples = w1 * temperature + w2 * rainfall + w3 * humidity`

NOTE: This equation is an approximation since the actual relationship may not necessarily be linear, and there may be other factors involved. But a simple linear model like this often works well in practice.

Given some climate data for a region, we can now predict the yield of apples. Here's some sample data:

| Region | Temp. (F) | Rainfall (mm) | Humidity (%) |
|--------|------------|-----------------|----------------|
| Kanto | 73 | 67 | 43 |
| Johto | 91 | 88 | 64 |
| Hoenn | 87 | 134 | 58 |
| Sinnoh | 102 | 43 | 37 |
| Unova | 69 | 96 | 70 |


We can find out the yeild of appples in the basic way....


In [41]:
# We can simply apply values to weights such as... 

w1, w2, w3 = 0.3, 0.2, 0.5

# Then we can define some variables to record climate data for a region

kanto_temp = 73
kanto_rainfall = 67
kanto_humid = 43

# Then we calculate the yeild fo apples using the linear equation...

kanto_apple_yield = w1 * kanto_temp + w2 * kanto_rainfall + w3 * kanto_humid
print(f"The expected yield of apples in the Kanto Region is {round(kanto_apple_yield)}")

The expected yield of apples in the Kanto Region is 57


To **simplify** this procedure, we can represent the data from each region in _vectors_ (aka list of numbers). 

Otherwise, there would be far too many varibles to be dealing with. In the running example, we took what would be $18$ variables and turned that into $6$ vectors. 

In [42]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

weights = [w1, w2, w3]

We can now write a function `crop_yield` to calcuate the yield of apples (or any other crop) given the climate data and the respective weights.

In [43]:
def crop_yeild(region, weights): 
    result = 0
    for r, w in zip(region, weights): 
        result += r*w
    return result

print(f"The region of Unova is expected to yield {round(crop_yeild(unova, weights))} crops. ")

The region of Unova is expected to yield 75 crops. 


In [44]:
# playing around with the `zip()` function. 

numbers = [1, 2, 3]
letters = ['a', 'b', 'c']
zipped = zip(numbers, letters)

print(list(zipped))

print(" ")

for n, l in zip(numbers, letters): 
    print(n, l, n*l)

[(1, 'a'), (2, 'b'), (3, 'c')]
 
1 a a
2 b bb
3 c ccc


### ii. Transitioning from Python lists to Numpy arrays

In the previous `crop_yeild()` fct, the calculation that was happening within was a _dot product_. 

The Numpy library provides a built-in function to compute the dot product of two vectors. So, let's convert the lists into Numpy arrays...


In [2]:
import numpy as np

In [46]:
kanto = np.array([73, 67, 43])
johto = np.array([91, 88, 64])
hoenn = np.array([87, 134, 58])
sinnoh = np.array([102, 43, 37])
unova = np.array([69, 96, 70])

weights = np.array([w1, w2, w3])

# **NOTE**
# Just like lists, numpy arrays also supports the indexing notations
print(f"On average, the temperature in Sinnoh is {sinnoh[0]} F")

On average, the temperature in Sinnoh is 102 F


### iii. Operating on Numpy arrays

We can now summarize the whole `crop_yield` fct into one line...


In [47]:
kanto_crop_yield = np.dot(kanto, weights)
print(kanto_crop_yield)

# is equivalent to 

kanto_crop_yield_2 = (kanto * weights).sum()
print(kanto_crop_yield_2)

56.8
56.8


In [48]:
# you can also summarize all elements w/in a vector (as seen above)

print(weights)
print(" ")

print(weights.sum())


[0.3 0.2 0.5]
 
1.0


### iv. Benefits of using Numpy

Numpy arrays offer the following benefits over Python lists for operating on numerical data:

- **Ease of use**: You can write small, concise, and intuitive mathematical expressions like `np.dot(kanto, weights)` or `(kanto * weights).sum()` rather than using loops & custom functions like `crop_yield`.
- **Performance**: Numpy operations and functions are implemented internally in C++, which makes them much faster than using Python statements & loops that are interpreted at runtime

Here's a comparison of dot products performed using Python loops vs. Numpy arrays on two vectors with a million elements each.

In [49]:
# Python List
py_list_1 = list(range(1000000))
py_list_2 = list(range(1000000, 2000000))

# Numpy Array
np_arr_1 = np.array(py_list_1)
np_arr_2 = np.array(py_list_2)

In [50]:
%%time
# Timing dot product w/ python lists
result = 0
for x, y in zip(py_list_1, py_list_2):
    result += x*y
print(result)

833332333333500000
CPU times: user 238 ms, sys: 2.52 ms, total: 241 ms
Wall time: 265 ms


In [51]:
%%time
# Timing dot product w/ numpy arrays
print(np.dot(np_arr_1, np_arr_2))

833332333333500000
CPU times: user 2.84 ms, sys: 2 ms, total: 4.84 ms
Wall time: 7.24 ms


Therefore, as shown, numpy arrays are MUCH faster to calculate with. Which becomes incredibly useful with larger data sets. 

And before the example above, we showed which much easier it is to use, reducing the number of variables significantly. 

## II. Multi-Dimensional Numpy Arrays 

To illustrate the use of multi-dim'l array, I will now represent the climate data for all the regions using a single 2-dimensional Numpy array (aka a 2x2 matrix)...

In [52]:
# 1-dim'l array

weights = np.array([0.3, 0.2, 0.5])

print(weights.shape)
weights.dtype

(3,)


dtype('float64')

In [53]:
# 2-dim'l array aka a matrix

climate_data = np.array([[73, 67, 43],
                        [91, 88, 64], 
                        [87, 134, 58], 
                        [102, 43, 37], 
                        [69, 96, 70]])

print(climate_data.shape)
climate_data.dtype

(5, 3)


dtype('int64')

In [54]:
# 3-dim's array/matrix

arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[11.5, 12.5, 13.5],
     [13.5, 14.5, 15.5]] ])

print(arr3.shape)
arr3.dtype

(2, 2, 3)


dtype('float64')

**Now** we can predict the yeild of crops in al the regions at once using the numpy arrays/matrices...

In [55]:
yield_of_crops = np.matmul(climate_data, weights)
print(yield_of_crops)

[56.8 76.9 81.9 57.7 74.9]


**Or** you can use the `@` operator which performs matrix multplication...

In [56]:
yield_of_crops_2 = climate_data @ weights
print(yield_of_crops_2)

[56.8 76.9 81.9 57.7 74.9]


### i. Working with CSV data

Numpy also provides helper functions reading from & writing to files. With this we can download a file called `climate.txt`, which contains $10,000$ climate measurements (temperature, rainfall & humidity) in the following format:

```
temperature,rainfall,humidity
25.00,76.00,99.00
39.00,65.00,70.00
59.00,45.00,77.00
84.00,63.00,38.00
66.00,50.00,52.00
41.00,94.00,77.00
91.00,57.00,96.00
49.00,96.00,99.00
67.00,20.00,28.00
...
```

This format of storing data is known as *comma-separated values* or **CSV**.

**CSVs**: A comma-separated values (CSV) file is a delimited text file that uses a comma to separate values. Each line of the file is a data record. Each record consists of one or more fields, separated by commas. A CSV file typically stores tabular data (numbers and text) in plain text, in which case each line will have the same number of fields. (Wikipedia)

To read this file into a numpy array, we can use the `genfromtxt` function. We can get this from the `urllib` module which offers most of the help needed for anything url related


In [3]:
import urllib.request

urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7f9768909d30>)

In [58]:
# Now to covert this csv into a numpy array...

climate_data = np.genfromtxt('climate.txt', delimiter = ',', skip_header=1)

print(climate_data.shape)
climate_data

(10000, 3)


array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [59]:
# NOW lets caclulate the yield of crops for this huge region data set...

yields = climate_data @ weights 

print(yields.shape)
        # we can see a vector here 
yields

(10000,)


array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [60]:
# Let's try to add `yields` to `climate_data` as a 4th column using `np.concatenate`...

climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

print(climate_results.shape)
climate_results

(10000, 4)


array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

A few notes here...

- Since we wish to add new columns, we pass the argument `axis=1` to `np.concatenate`. The `axis` argument specifies the dimension for concatenation.
- The arrays should have the same number of dimensions, and the same length along each except the dimension used for concatenation. We use the `np.reshape` function to change the shape of `yields` from $(10000,)$ to $(10000,1)$.

Below, I play around with `np.concatenate` and `.rehape()`

In [61]:
# playing around w/ `np.concatenate` and `.rehape()`

matrix1 = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
matrix2 = np.array([['a', 'b', 'c']])

# adding an array to a data set as a column
print(np.concatenate((matrix1, matrix2.reshape(3, 1)), axis=1))
print(' ')
print(np.concatenate((matrix1, matrix2.reshape(3, 1)), axis=1).shape )

print(' ')

# adding an array to a data set as a row
print(np.concatenate((matrix1, matrix2.reshape(1, 3)), axis=0))
print(' ')
print(np.concatenate((matrix1, matrix2.reshape(1, 3)), axis=0).shape )

[['1' '2' '3' 'a']
 ['4' '5' '6' 'b']
 ['7' '8' '9' 'c']]
 
(3, 4)
 
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']
 ['a' 'b' 'c']]
 
(4, 3)


After doing soem data manipulation, lets save what we did...

In [62]:
np.savetxt('climate_results.txt', 
          climate_results, 
          fmt = '%.2f',    # formating : floating points are at two decimal places. 
          header = 'temperature,rainfall,humidity,yeild_apples', 
          comments = '')

Numpy provides hundreds of functions for performing operations on arrays. Here are some commonly used functions:

- Mathematics: np.sum, np.exp, np.round, arithemtic operators
- Array manipulation: np.reshape, np.stack, np.concatenate, np.split
- Linear Algebra: np.matmul, np.dot, np.transpose, np.eigvals
- Statistics: np.mean, np.median, np.std, np.max

> How to find the function you need? The easiest way to find the right function for a specific operation or use-case is to do a web search. For instance, searching for *"How to join numpy arrays"* leads to this tutorial on array concatenation.

You can find a full list of array functions [here](https://numpy.org/doc/stable/reference/routines.html)

In [4]:
from numpy import linalg as la

In [64]:
matrix = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])
# vector = np.array([10, 11, 12])
v_matrix = np.array([[10, 11, 12], 
                    [13, 14, 15], 
                    [16, 17, 18]])

arry1 = np.array([1, 2, 3])
arry2 = np.array([4, 5, 6])

# take the ___exponential___ of every element within the matrix
print(np.exp(matrix))
print("")


# use `np.stack` to ___stack___ matricies of same size together along an axis that doesnt exist 
#       (i.e. where np.concatenate adds array as rows or columns, np.stack adds to for example 3rd-dim/3rd axis)
print(np.stack((matrix, v_matrix)))
print(np.stack((matrix, v_matrix)).shape)
print("")
print(np.stack((matrix, v_matrix), axis=-1))
print(np.stack((matrix, v_matrix), axis=-1).shape)


[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
(2, 3, 3)

[[[ 1 10]
  [ 2 11]
  [ 3 12]]

 [[ 4 13]
  [ 5 14]
  [ 6 15]]

 [[ 7 16]
  [ 8 17]
  [ 9 18]]]
(3, 3, 2)


### ii. Arithmetic operations, broadcasting and comparison

#### Arithmetic operations

Numpy arrays support arithmetic operators like `+`, `-`, `*`, etc. You can perform an arithmetic operation with a single number (also called scalar) or with another array of the same shape. Operators make it easy to write mathematical expressions with multi-dimensional arrays.

In [65]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

# Adding a scalar
print('Adding a scalar (arr2+3): ')
print(arr2 + 3)
print('')

# Element-wise subtraction
print('Element-wise subtraction (arr3-arr2): ')
print(arr3 - arr2)
print(' ')

# Division by scalar
print('Division by scalar (arr2 / 2): ')
print(arr2 / 2)
print(' ')

# Element-wise multiplication
print('Element-wise multiplication (arr2 * arr3): ')
print(arr2 * arr3)
print(' ')

# Modulus with scalar
print('Modulus with scalar (arr2 % 4): ')
print(arr2 % 4)
print(' ')

Adding a scalar (arr2+3): 
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12  4  5  6]]

Element-wise subtraction (arr3-arr2): 
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
 
Division by scalar (arr2 / 2): 
[[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [4.5 0.5 1.  1.5]]
 
Element-wise multiplication (arr2 * arr3): 
[[ 11  24  39  56]
 [ 75  96 119 144]
 [171  11  24  39]]
 
Modulus with scalar (arr2 % 4): 
[[1 2 3 0]
 [1 2 3 0]
 [1 1 2 3]]
 


#### Array Broadcasting

Numpy arrays also support _broadcasting_, allowing arithmetic operations between two arrays with different numbers of dimensions but compatible shapes. Let's look at an example to see how it works.

Given `arr2` that has a shape of $(3, 4)$ and a new array `arr4 = np.array([4, 5, 6, 7])` that has a shape of $(4, )$. We can see that the shapes are different, but bc of _broadcasting_....

When the expression `arr2 + arr4` is evaluated, `arr4` (which has the shape $(4, )$) is replicated three times to match the shape $(3, 4)$ of `arr2`. Numpy performs the replication without actually creating three copies of the smaller dimension array, thus improving performance and using lower memory.

Therefore, numpy turns 
> `arr4 = np.array([4, 5, 6, 7])`

into
> `arr4_rearranged = np.array([[4, 5, 6, 7], 
>                             [4, 5, 6, 7], 
>                             [4, 5, 6, 7] ])`

Then it performs the operation. Let's see it in action. 

In [66]:
arr4 = np.array([4, 5, 6, 7])

print(arr2 + arr4)

[[ 5  7  9 11]
 [ 9 11 13 15]
 [13  6  8 10]]


But, given another new array `arr5 = np.array([7, 8]) that has a shape of  (2,)`, we can see that even if numpy rearranges it to....
> `arr5_rearranged = np.array([[7, 8], 
>                             [7, 8], 
>                             [7, 8] ])`

the shape now becomes $(3, 2)$ whic still doesn tmatch the shape of `arr2` which is $(3, 4)$. 

(NOTE: Learn more about broadcasting [here](https://numpy.org/doc/stable/user/basics.broadcasting.html).) 

Therefore, numpy cannot perform this operation....

In [67]:
arr5 = np.array([7, 8])

print(arr2 + arr5)

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

#### Array Comparison

Numpy arrays also support comparison operations like $==$, $!=$, $>$ etc. 

The result is an array of booleans.

In [68]:
arr1 = np.array([[1, 2, 3], 
                 [3, 4, 5]])
arr2 = np.array([[2, 2, 3], 
                 [1, 2, 5]])

arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [69]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [70]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [71]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

_Array comparison_ is frequently used to count the number of equal elements in two arrays using the sum method. Remember that `True` evaluates to $1$ and `False` evaluates to $0$ when booleans are used in arithmetic operations.

In [72]:
(arr1 == arr2).sum()

# the result is 3 therefore there are 3 elemets that are equaivalent in the same place in both matrices.  

3

### iii. Array indexing and slicing

Numpy extends Python's list indexing notation using `[]` to multiple dimensions in an intuitive fashion. You can provide a comma-separated list of indices or ranges to select a specific element or a subarray (also called a _slice_) from a Numpy array.

In [73]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

arr3.shape

(3, 2, 4)

In [74]:
# Extracting a single element 
#    - second layer, 
#    - second row, 
#    - third column

arr3[1, 1, 2]

36.0

In [75]:
# Extracting a subarray using ranges...
#    - from the second face to last face
#    - first row up to (and not including) the second
#    - first column up to (and not including) the third

arr3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [76]:
# Mixing indices and ranges

print('arr3[1:, 1, 3] = ')
print('                ', arr3[1:, 1, 3])
    # from the second layer to the last
    # the second row
    # the 4th column 
            # = array([18, 43])
print(' ')


print('arr3[1:, 1, :3] = ')
print(arr3[1:, 1, :3])
    # from the second layer to the last
    # the second row
    # from first column up to (but not including) the 4th column 
            # = array( [63, 92, 36], [17, 18, 19.5] )
print(' ')

print('arr3[1, 0, 1::2] = ')
print("                 ", arr3[1, 0, 1::2])
    # second layer
    # first row
    # starting in the second column, select that second element
print(' ')

arr3[1:, 1, 3] = 
                 [18. 43.]
 
arr3[1:, 1, :3] = 
[[63.  92.  36. ]
 [17.  18.  19.5]]
 
arr3[1, 0, 1::2] = 
                  [16. 21.]
 


In [77]:
# You can even index fewer parameters than the dimensions of the matrix...

print('arr3[1] = ')
print(arr3[1])
    # will extract the whole second layer

print(' ')

print('arr3[:2, 1] = ')
print(arr3[:2, 1])
    # will extract...
            # from first layer up to (not including) the 3rd layer
            # second row

arr3[1] = 
[[15. 16. 17. 21.]
 [63. 92. 36. 18.]]
 
arr3[:2, 1] = 
[[13. 14. 15. 19.]
 [63. 92. 36. 18.]]


## III. Other Methods of Creating Numpy Arrays

We have seen arrays being made with...
- `np.array( [ ] )` method : the most basic and easiest way of creating arrays. 
- `genfromtxt` function : creates arrasy using data from data file (csv in this lecture) 

Let's see what else we can use...

In [79]:
# Creating an array/matrix of ___all zero elements___

np.zeros((3, 4))
        # in here, we put in the dimentions of array/matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [82]:
# Creating an array/matrix of ___all one elements___

np.ones([2, 2, 3])
        # in here, we put in the dimentions of array/matrix

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [84]:
# Create an ___identity matrix___

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [91]:
# Create a vector/array with ___random values___

print(np.random.rand(5))
    # when using `np.random.rand()`, you will only get postive numbers

print(" ")

print(np.random.randn(3, 4))
    # when using `np.random.rand()`, you will get postive AND negative numbers

[0.73350288 0.36330228 0.25147237 0.2056564  0.37803493]
 
[[-1.08536816  0.79498509 -0.50040239 -1.47178971]
 [-0.41833284  0.97559848 -0.64406973  0.7188176 ]
 [-0.02628912  0.7635086  -0.97957703  1.66089754]]


In [93]:
# Create a matrix of any size where every elemeents is fixed...
np.full([3, 2], 42)

array([[42, 42],
       [42, 42],
       [42, 42]])

In [99]:
# create a matrix with range given start/endpoints and step size if needed. 
print(np.arange(10, 90, 3))

print(' ')

# can also rearrange this into a matrix w/ dim's of your choosing
print(np.arange(10, 90, 2).reshape(5, 8))

[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88]
 
[[10 12 14 16 18 20 22 24]
 [26 28 30 32 34 36 38 40]
 [42 44 46 48 50 52 54 56]
 [58 60 62 64 66 68 70 72]
 [74 76 78 80 82 84 86 88]]


In [103]:
# Get from start_postition to end_position in n-steps (9 steps in this problem)
np.linspace(3, 27, 9).reshape(3, 3)

array([[ 3.,  6.,  9.],
       [12., 15., 18.],
       [21., 24., 27.]])

# Assignment 2

There is a Assignment 2 for Numpy called [Numpy Array Operations](https://jovian.ai/aakashns/numpy-array-operations). 

Pick 5 interesting Numpy array functions by going through this [documentation](https://numpy.org/doc/stable/reference/routines.html). Then provide explainations and 3 examples (one beign an example for when the fct fails). 

The functions I will be choosing are...

### Function 1 - numpy.linalg
Numy comes with many linear lagebra operations like...
- .det() : calculates determinate of an array
- .inv() : calculates inverse
- .eig()/.eigvals() : finds eig of array
- etc

In [5]:
# to get all the linear algebra features....
from numpy import linalg

In [128]:
ex_matrix = np.array([[2, -1], 
                     [-1, 2]])

print(linalg.det(ex_matrix))

print(" ")

print(linalg.inv(ex_matrix))

2.9999999999999996
 
[[0.66666667 0.33333333]
 [0.33333333 0.66666667]]


# 100 Exercises

[Link](https://jovian.ai/aakashns/100-numpy-exercises)

Here's a few i decided to tackle

In [145]:
# 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
q_6 = np.zeros(10)
q_6[4] = 1
print("Question 6: ")
print(q_6)
print(" ")

# 7. Create a vector with values ranging from 10 to 49 (★☆☆)
q_7 = np.arange(10, 50)
print("Question 7: ")
print(q_7)
print(" ")

# 8. Reverse a vector (first element becomes last) (★☆☆)
q_8 = np.flip(q_7)
# OR
# q_8 = q_7[::-1]
print("Question 8: ")
print(q_8)
print(" ")

# 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
given_10 = np.array([1,2,0,0,4,0])
q_10 = np.nonzero(given_10)
print("Question 10: ")
print(q_10)
print(" ")

Question 6: 
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 
Question 7: 
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
 
Question 8: 
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
 
Question 10: 
(array([0, 1, 4]),)
 


In [228]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
array_13 = np.random.rand(10,10)
print("Question 13: ")
print(f"The max value in this array is {np.max(array_13)}")
print(f"The min value in this array is {np.min(array_13)}")
print(" ")


# 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
q_15 = np.ones((4, 4))
for i in range(len(q_15)):
    if i!= 0 and i != len(q_15) - 1:
        for j in range(len(q_15)):
            if j!= 0 and j != len(q_15) - 1:
                q_15[i, j] = 0
print("Question 13: ")
print(q_15)
print(" ")


# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
q_18 = np.zeros((8, 8), dtype = int)
q_18[1::2, ::2] = 1
q_18[::2, 1::2] = 1
print("Question 18: ")
print(q_18)
print(" ")



Question 13: 
The max value in this array is 0.995337994606089
The min value in this array is 0.0025451845663834183
 
Question 13: 
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
 
Question 18: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
 


In [281]:
# 22. Normalize a 5x5 random matrix (★☆☆)
q_22 = np.random.rand(5,5)
q_22 = (q_22 - np.mean (q_22)) / (np.std(q_22) )
print("Question 22: ")
print(q_22)
print(" ")


# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
q_23 = np.dtype([("r", np.ubyte, 1), 
                ("g", np.ubyte, 1), 
                ("b", np.ubyte, 1), 
                ("a", np.ubyte, 1)])


# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
arr1_q_24 = np.arange(1, 16).reshape(5, 3)
arr2_q_24 = np.arange(16, 22).reshape(3, 2)
q_24 = arr1_q_24 @ arr2_q_24
print("Question 24: ")
print(q_24)
print(" ")


# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
q_25 = np.arange(11)
q_25[(q_25 > 3) & (q_25 < 8)] *= -1
print("Question 25: ")
print(q_25)
print(" ")


# 30. How to find common values between two arrays? (★☆☆)
arr1_q_30 = np.array([24, 60, 58, 23, 45])
arr2_q_30 = np.array([50, 46, 45, 65, 60, 78])
q_30 = np.intersect1d(arr1_q_30, arr2_q_30)
print("Question 30: ")
print(q_30)
print(" ")


Question 22: 
[[ 0.8846352  -0.8071015  -0.64020349 -0.79080545  0.76247659]
 [ 0.29258139  0.37471931  1.37839186 -2.06387943 -0.38501781]
 [-1.09916443  0.05226903  1.21805728 -1.28452818  1.03539977]
 [ 1.46126782  0.2020224   0.72585082  0.39658743  1.1116696 ]
 [-1.21523565 -1.15292383 -1.55253737  0.33981081  0.75565783]]
 
Question 24: 
[[112 118]
 [274 289]
 [436 460]
 [598 631]
 [760 802]]
 
Question 25: 
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
 
Question 30: 
[45 60]
 


<ipython-input-281-4752aa663573>:10: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  q_23 = np.dtype([("r", np.ubyte, 1),


In [35]:
# 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
print("Question 33: ")
print(f"Today is {np.datetime64('today', 'D')}")
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, "D")
print(f"Yesterday was {yesterday}")
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, "D")
print(f"Tomorrow is {tomorrow}")
            # you can do many amazing things with `np.datetime64()` and `np.timedelta64()`
print(" ")


# 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print("Question 34: ")
print(f"The month of july in 2016: {july_2016}")
print(" ")

Question 33: 
Today is 2021-11-07
Yesterday was 2021-11-06
Tomorrow is 2021-11-08
 
Question 34: 
The month of july in 2016: ['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']
 


In [71]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, 
#          and convert them to polar coordinates (★★☆)
q_44 = np.random.rand(10, 2)
X, Y = q_44[:,0], q_44[:, 1]
R = np.sqrt(X**2+Y**2).reshape(10,1)
T = np.arctan2(Y,X).reshape(10, 1)
q_44_polar = np.concatenate((R, T), axis=1)
print("Question 44: ")
print(q_44_polar)
print("")


# 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
q_45 = np.random.rand(10)
q_45[q_45.argmax()] = 0
print(q_45)

Question 44: 
[[1.14552316 1.05194854]
 [1.02549271 0.73306039]
 [1.28315353 0.84541938]
 [0.86122854 0.06896492]
 [0.39175376 0.4970777 ]
 [0.32865112 1.04884567]
 [0.93779553 0.06073634]
 [0.88320942 0.87419279]
 [0.15931197 1.25814543]
 [0.44564912 0.08314502]]

[0.23075992 0.67282272 0.01455762 0.91121524 0.53341547 0.12416094
 0.12005092 0.         0.46311404 0.8819677 ]


In [77]:
# 72. How to swap two rows of an array? (★★★)
q_72 = np.arange(25).reshape((5,5))
print("Question 72: ")
print("Before row swap....")
print(q_72)
print("After row swap....")
q_72[[2,4]]=q_72[[4, 2]]
print(q_72)

Question 44: 
Before row swap....
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
After row swap....
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]]
